// All 32 teams: abbreviation, full name, and words that identify the team in a headline.
export const TEAMS = [
  ['ARI', 'Arizona Cardinals', ['cardinals', 'arizona']],
  ['ATL', 'Atlanta Falcons', ['falcons', 'atlanta']],
  ['BAL', 'Baltimore Ravens', ['ravens', 'baltimore']],
  ['BUF', 'Buffalo Bills', ['bills', 'buffalo']],
  ['CAR', 'Carolina Panthers', ['panthers', 'carolina']],
  ['CHI', 'Chicago Bears', ['bears', 'chicago']],
  ['CIN', 'Cincinnati Bengals', ['bengals', 'cincinnati']],
  ['CLE', 'Cleveland Browns', ['browns', 'cleveland']],
  ['DAL', 'Dallas Cowboys', ['cowboys', 'dallas']],
  ['DEN', 'Denver Broncos', ['broncos', 'denver']],
  ['DET', 'Detroit Lions', ['lions', 'detroit']],
  ['GB', 'Green Bay Packers', ['packers', 'green bay']],
  ['HOU', 'Houston Texans', ['texans', 'houston']],
  ['IND', 'Indianapolis Colts', ['colts', 'indianapolis']],
  ['JAX', 'Jacksonville Jaguars', ['jaguars', 'jacksonville', 'jags']],
  ['KC', 'Kansas City Chiefs', ['chiefs', 'kansas city']],
  ['LV', 'Las Vegas Raiders', ['raiders', 'las vegas']],
  ['LAC', 'Los Angeles Chargers', ['chargers']],
  ['LAR', 'Los Angeles Rams', ['rams']],
  ['MIA', 'Miami Dolphins', ['dolphins', 'miami']],
  ['MIN', 'Minnesota Vikings', ['vikings', 'minnesota']],
  ['NE', 'New England Patriots', ['patriots', 'new england', 'pats']],
  ['NO', 'New Orleans Saints', ['saints', 'new orleans']],
  ['NYG', 'New York Giants', ['giants']],
  ['NYJ', 'New York Jets', ['jets']],
  ['PHI', 'Philadelphia Eagles', ['eagles', 'philadelphia']],
  ['PIT', 'Pittsburgh Steelers', ['steelers', 'pittsburgh']],
  ['SF', 'San Francisco 49ers', ['49ers', 'niners', 'san francisco']],
  ['SEA', 'Seattle Seahawks', ['seahawks', 'seattle']],
  ['TB', 'Tampa Bay Buccaneers', ['buccaneers', 'bucs', 'tampa bay']],
  ['TEN', 'Tennessee Titans', ['titans', 'tennessee']],
  ['WAS', 'Washington Commanders', ['commanders', 'washington']],
].map(([abbr, name, words]) => ({ abbr, name, words }));
